### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by mesarcik** [mesarcik/ROAD#15]
# Description:
There are currently two separate branches that are being used for evaluation, the one is for SSL pretraining and the other is for evaluting the fine tuned models. I need to merge them so that all fine tuning and pretraining is done simultaneously. 

## TO-DO:
- [x] Merge main and the code from the class removal 
- [x] Update resnet structure (remove position classifier from the model) 
- [x] Add code for changing model backbones
- [x] Determine best way to evaluate supervised classifier and detector 
- [x] Refactor VAE evaluation code by using the `eval_knn` function

## Tests:
- Ensure the performance of the models as the same as before refactoring
